ministryofjustice/hmpps-nomis-sync-dashboard

integration_tests/integration/startVisitsMigration.spec.ts
integration_tests/mockApis/nomisPrisonerApi.ts
integration_tests/pages/visits-migration/startVisitsMigration.ts
integration_tests/plugins/index.ts
package.json
server/@types/express/index.d.ts
server/@types/nomisPrisoner/index.d.ts
server/app.ts
server/index.ts
server/routes/testutils/appSetup.ts
server/routes/testutils/mockNomisPrisonerService.ts
server/routes/visitMigration/startVisitsMigrationValidator.test.ts
server/routes/visitMigration/startVisitsMigrationValidator.ts
server/routes/visitMigration/visitMigrationController.ts
server/routes/visitMigration/visitMigrationRouter.ts
server/services/nomisPrisonerService.test.ts
server/services/nomisPrisonerService.ts
server/validation/validation.ts
server/views/pages/visits/startVisitsMigration.njk

Now calls the NOMIS prisoner API to get the count and display as a info message

SDI-119 Get estimated count and use client credentials

---

integration_tests/integration/startVisitsMigration.spec.ts
integration_tests/mockApis/nomisMigrationApi.ts
integration_tests/pages/visits-migration/startVisitsMigrationConfirmation.ts
integration_tests/plugins/index.ts
server/@types/express/index.d.ts
server/@types/migration/index.d.ts
server/config.ts
server/data/restClient.ts
server/routes/visitMigration/visitMigrationController.ts
server/services/nomisMigrationService.test.ts
server/services/nomisMigrationService.ts
server/views/pages/visits/startVisitsMigrationConfirmation.njk

* Launches a migration and returns migrationId and count

SDI-119 Launch new migration

---

integration_tests/integration/visitsMigrationFailures.spec.ts
integration_tests/mockApis/nomisMigrationApi.ts
integration_tests/pages/visits-migration/visitsMigrationFailures.ts
integration_tests/plugins/index.ts
server/@types/migration/index.d.ts
server/routes/visitMigration/visitMigrationController.ts
server/routes/visitMigration/visitMigrationRouter.ts
server/services/nomisMigrationService.test.ts
server/services/nomisMigrationService.ts
server/utils/nunjucksSetup.ts
server/views/pages/visits/startVisitsMigrationConfirmation.njk
server/views/pages/visits/visitsMigrationFailures.njk

Added basic view of messages on DLQ
Eventually there will be link from history page to get to this page

SDI-119 View DLQ messages

---

helm_deploy/hmpps-nomis-sync-dashboard/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.ts
server/routes/visitMigration/visitMigrationRouter.ts
server/routes/visitMigration/visitsMigrationController.test.ts
server/routes/visitMigration/visitsMigrationController.ts
server/utils/applicationInsightsUrlBuilder.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/visits/visitsMigrationFailures.njk

* Subscription ID will be manually added to secrets
Link will open AppSights for exception related to message:

SDI-119 Added link to AppInsights query

---

server/routes/visitMigration/visitsMigrationController.ts

Improvement to count by using a distinct so same visits are not counted twice

SDI-119-AppInsights

---

integration_tests/mockApis/nomisMigrationApi.ts
server/services/nomisMigrationService.test.ts
server/services/nomisMigrationService.ts

Service has change the location in info where queue name is found due to the IEP work

SDI-355 Queue name change

---

integration_tests/e2e/startIncentivesMigration.cy.ts
integration_tests/pages/incentives-migration/startIncentivesMigration.ts
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/routes/incentiveMigration/incentiveMigrationRouter.ts
server/routes/incentiveMigration/incentivesMigrationController.test.ts
server/routes/incentiveMigration/incentivesMigrationController.ts
server/routes/incentiveMigration/startIncentivesMigrationValidator.test.ts
server/routes/incentiveMigration/startIncentivesMigrationValidator.ts
server/validation/validation.ts
server/views/pages/incentives/startIncentivesMigration.njk

* just validates form
* doesn't do the preview page yet

SDI-355 Start incentives migration page

---

integration_tests/e2e/appointmentsMigration.cy.ts
integration_tests/e2e/appointmentsMigrationDetails.cy.ts
integration_tests/e2e/appointmentsMigrationFailures.cy.ts
integration_tests/e2e/startAppointmentsMigration.cy.ts
server/@types/dashboard/index.d.ts
server/routes/appointmentsMigration/appointmentsMigrationController.ts
server/routes/appointmentsMigration/appointmentsMigrationValidator.test.ts
server/routes/appointmentsMigration/appointmentsMigrationValidator.ts
server/routes/visitMigration/visitsMigrationController.ts
server/routes/visitMigration/visitsMigrationValidator.ts
server/services/nomisMigrationService.ts
server/utils/nunjucksSetup.ts
server/views/pages/appointments/appointmentsMigration.njk

Fully implemented filtering of migration history

SDIT-827 appointments-migration page filter issues

---

server/views/pages/appointments/appointmentsMigrationFailures.njk
server/views/pages/sentencing/sentencingMigrationFailures.njk
server/views/pages/visits/visitsMigrationFailures.njk

SDIT-865 Improve Get DLQ API in SQS lib

---

server/views/pages/activities/activitiesMigration.njk
server/views/pages/activities/activitiesMigrationDetails.njk
server/views/pages/activities/activitiesMigrationFailures.njk
server/views/pages/activities/startActivitiesMigration.njk
server/views/pages/activities/startActivitiesMigrationConfirmation.njk
server/views/pages/activities/startActivitiesMigrationPreview.njk
server/views/pages/allocations/allocationsMigration.njk
server/views/pages/allocations/allocationsMigrationDetails.njk
server/views/pages/allocations/allocationsMigrationFailures.njk
server/views/pages/allocations/startAllocationsMigration.njk
server/views/pages/allocations/startAllocationsMigrationConfirmation.njk
server/views/pages/allocations/startAllocationsMigrationPreview.njk

Which are just copied from an existing migration

SDIT-983 Add templates for activities and allocations migrations

---

integration_tests/e2e/activitiesMigration.cy.ts
integration_tests/pages/activities-migration/activitiesMigration.ts
server/routes/allocationsMigration/allocationsMigrationController.ts
server/views/pages/activities/activitiesMigration.njk
server/views/pages/allocations/allocationsMigration.njk

SDIT-1101 allocations link and instructions

---

integration_tests/e2e/activitiesMigration.cy.ts
integration_tests/e2e/activitiesMigrationFailures.cy.ts
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/mockApis/nomisMigrationApi.ts
integration_tests/mockApis/nomisPrisonerApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/routes/activitiesMigration/activitiesMigrationRouter.ts
server/services/nomisPrisonerService.test.ts
server/services/nomisPrisonerService.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk

SDIT-1348 Check feature switch status for activities migration preview

---

cypress.config.ts
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/mockApis/activitiesApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/routes/activitiesMigration/activitiesMigrationRouter.ts
server/routes/testutils/mockActivitiesService.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/services/index.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk

The new feature is **DPS feature switch not turned on for WWI**.
(I'll try and sort out that horrible formatting of the `Activate Prison` button soon)

SDIT-1349 Add Activities prison feature switch check to UI

---

feature.env
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/mockApis/activitiesApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk

New feature is **DPS has no pay bands for prison WWI.**.  Also tidied up the **Activate prison** button.

SDIT-1349 Add Activities prison pay band check to UI

---

integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/mockApis/activitiesApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk

New feature is **DPS has no slot times configured for prison WWI.**

SDIT-1349 Add Activities prison regime check to UI (slot times)

---

assets/js/page-enhancements.js
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/mockApis/nomisMigrationApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/@types/migration/index.d.ts
server/@types/migrationImport/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/services/nomisMigrationService.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk
server/views/partials/layout.njk

The **Found suspended allocations** message now appears in the migration preview checks:
And clicking on the **Copy** button adds the following to the Clipboard:
```
Activity Description, Activity ID, Prisoner Number,
AM & PM A Hotplate Assistant, 81641, G8044VV,
AM & PM B Wing Cleaner, 81672, G0065UT,
AM & PM B Wing Cleaner, 81672, G8271VD,
AM & PM C Wing Cleaner, 81674, G0803GG,
AM & PM C Wing Cleaner, 81674, G6458GA,
AM & PM C Wing Cleaner, 81674, G9918GE,
AM & PM G Hotplate Assistant, 81650, G2067VO,
AM & PM G Wing OAP, 157860, G4110UF,
AM & PM PIDS A Wing, 160355, G4394VJ,
...etc
```

SDIT-1350 Report on activity migration suspended allocations

---

integration_tests/e2e/health.cy.ts
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/e2e/startAppointmentsMigration.cy.ts
integration_tests/mockApis/activitiesApi.ts
integration_tests/mockApis/nomisPrisonerApi.ts
integration_tests/pages/appointments-migration/startAppointmentsMigrationPreview.ts
server/@types/express/index.d.ts
server/routes/appointmentsMigration/appointmentsMigrationController.test.ts
server/routes/appointmentsMigration/appointmentsMigrationController.ts
server/routes/appointmentsMigration/appointmentsMigrationRouter.ts
server/services/healthCheck.ts
server/views/pages/appointments/startAppointmentsMigrationPreview.njk

Checks the NOMIS APPOINTMENTS feature switch for all prisons selected for migration:
Each Activate Prison link should then turn on the feature switch.

SDIT-1355 check appointment feature switch

---

server/@types/nomisPrisoner/index.d.ts
server/@types/nomisPrisonerImport/index.d.ts
server/services/nomisPrisonerService.ts
server/views/pages/alerts/startAlertsMigration.njk
server/views/pages/alerts/startAlertsMigrationPreview.njk

Also use prisoner ids endpoint for count

SDI-1688 Remove alert filter.

---

assets/js/index.js
assets/js/page-enhancements.js
esbuild/esbuild.config.js
server/views/pages/allocations/startAllocationsMigrationPreview.njk
server/views/pages/appointments/startAppointmentsMigrationPreview.njk
server/views/partials/layout.njk

Reverts ministryofjustice/hmpps-nomis-sync-dashboard#196

Revert "SDIT-2037: 🎨 Rewrite javascript after esbuild introduction"

---

assets/js/copy-text.js
assets/js/index.js
assets/js/page-enhancements.js
esbuild/esbuild.config.js
integration_tests/e2e/startActivitiesMigration.cy.ts
integration_tests/e2e/startAppointmentsMigration.cy.ts
integration_tests/pages/activities-migration/startActivitiesMigration.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
integration_tests/pages/appointments-migration/startAppointmentsMigration.ts
integration_tests/pages/appointments-migration/startAppointmentsMigrationPreview.ts
integration_tests/pages/copyTextPage.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk
server/views/pages/allocations/startAllocationsMigrationPreview.njk
server/views/pages/appointments/startAppointmentsMigrationPreview.njk
server/views/partials/layout.njk

Reverts ministryofjustice/hmpps-nomis-sync-dashboard#197

Revert "Revert "SDIT-2037: 🎨 Rewrite javascript after esbuild introduction""

---

integration_tests/e2e/activitiesMigrationStart.cy.ts
integration_tests/e2e/allocationsMigrationStart.cy.ts
integration_tests/e2e/appointmentsMigrationStart.cy.ts
integration_tests/e2e/csipMigrationStart.cy.ts
integration_tests/e2e/incidentsMigrationStart.cy.ts
integration_tests/e2e/prisonPersonMigrationStart.cy.ts
integration_tests/e2e/sentencingMigrationStart.cy.ts
integration_tests/e2e/visitsMigrationStart.cy.ts

SDIT-2037: ✅ Rename tests to fit with structure of other tests

---

assets/js/copy-text.js
integration_tests/e2e/activitiesMigrationStart.cy.ts
integration_tests/mockApis/nomisPrisonerApi.ts
integration_tests/pages/activities-migration/startActivitiesMigrationPreview.ts
server/@types/express/index.d.ts
server/@types/nomisPrisoner/index.d.ts
server/@types/nomisPrisonerImport/index.d.ts
server/routes/activitiesMigration/activitiesMigrationController.test.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/services/nomisPrisonerService.test.ts
server/services/nomisPrisonerService.ts
server/views/pages/activities/startActivitiesMigrationPreview.njk

SDIT-2166 New preview warning to check for activities without schedule rules

---

server/data/contactPersonNomisMigrationClient.ts
server/data/contactPersonNomisPrisonerClient.ts
server/data/contactPersonProfileDetailsNomisMigrationClient.ts
server/data/contactPersonProfileDetailsNomisPrisonerClient.ts
server/data/corePersonNomisMigrationClient.ts
server/data/index.ts
server/services/contactperson/contactPersonNomisMigrationService.ts
server/services/contactperson/contactPersonNomisPrisonerService.ts
server/services/contactperson/profiledetails/contactPersonProfileDetailsNomisMigrationService.ts
server/services/contactperson/profiledetails/contactPersonProfileDetailsNomisPrisonerService.ts
server/services/coreperson/corePersonNomisMigrationService.ts
server/services/index.ts

- **SDIT-2709: ♻️ Switch to hmpps rest client**
- **SDIT-2709: ♻️ Switch to hmpps rest client (2)**

SDIT-2709: ♻️ Switch to hmpps rest client (2)

---

server/@types/express/index.d.ts
server/@types/migrationImport/index.d.ts
server/data/activitiesNomisMigrationClient.ts
server/routes/activitiesMigration/activitiesMigrationController.ts
server/routes/activitiesMigration/activitiesMigrationRouter.ts
server/routes/activitiesMigration/moveActivityStartDateValidator.test.ts
server/routes/activitiesMigration/moveActivityStartDateValidator.ts
server/services/activities/activitiesNomisMigrationService.ts
server/views/pages/activities/activitiesMigration.njk
server/views/pages/activities/moveActivityStartDate.njk
server/views/pages/activities/startActivitiesMigrationPreview.njk

Move start date shows the following screen:

SDIT-2580 Add facility to move migrated activity start date
